<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>CleanPathfinding</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>net48</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>12.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="Assembly-CSharp" />
    <Reference Include="0Harmony" />
    <Reference Include="UnityEngine.CoreModule" />
    <Reference Include="System.Core" />
    <Reference Include="UnityEngine.IMGUIModule" />
  </ItemGroup>
</Project>