<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <LangVersion>7.3</LangVersion>
    <AssemblyName>RimMT.RC2Tail</AssemblyName>
    <RootNamespace>RimMTRC2Tail</RootNamespace>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <OutputPath>../../1.5/Assemblies/</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Krafs.Rimworld.Ref" Version="1.5.4063" />
    <PackageReference Include="Lib.Harmony" Version="2.3.3" />
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies.net472" Version="1.0.3" PrivateAssets="All" />
  </ItemGroup>
</Project>
