using RimWorld;
using System.Collections.Generic;
using Verse;
using Verse.AI;

namespace PogoAI.Patches
{
    internal enum JobLoopDecision
    {
        Keep,
        Suppress,
        FallbackVanilla
    }

    /// <summary>
    /// Narrow guard for jobs generated by Smarter Raider AI's
    /// JobGiver_AITrashBuildingsDistant -> custom AISapper path.
    /// It deliberately does not patch Pawn_JobTracker globally.
    /// </summary>
    internal static class JobLoopGuard
    {
        private const int InvalidJobFallbackTicks = 30;
        private static readonly Dictionary<Pawn, int> vanillaFallbackUntilTick = new Dictionary<Pawn, int>();

        internal static bool IsMountTransition(Pawn pawn)
        {
            if (pawn == null)
            {
                return false;
            }

            JobDef currentDef = pawn.CurJobDef;
            return currentDef != null && currentDef.defName == "Mount";
        }

        internal static bool UseVanillaFallbackForNow(Pawn pawn)
        {
            if (pawn == null)
            {
                return false;
            }

            int untilTick;
            if (!vanillaFallbackUntilTick.TryGetValue(pawn, out untilTick))
            {
                return false;
            }

            int now = Find.TickManager?.TicksGame ?? 0;
            if (pawn.Destroyed || now >= untilTick)
            {
                vanillaFallbackUntilTick.Remove(pawn);
                return false;
            }

            return true;
        }

        internal static void BeginVanillaFallback(Pawn pawn)
        {
            if (pawn == null)
            {
                return;
            }

            int now = Find.TickManager?.TicksGame ?? 0;
            vanillaFallbackUntilTick[pawn] = now + InvalidJobFallbackTicks;
        }

        internal static JobLoopDecision ValidateGeneratedJob(Pawn pawn, ref Job job)
        {
            if (job == null)
            {
                return JobLoopDecision.Keep;
            }

            if (pawn == null || pawn.Destroyed || !pawn.Spawned || pawn.Map == null)
            {
                job = null;
                return JobLoopDecision.FallbackVanilla;
            }

            if (IsMountTransition(pawn))
            {
                job = null;
                return JobLoopDecision.Suppress;
            }

            if (IsSameCurrentJob(pawn, job))
            {
                job = null;
                return JobLoopDecision.Suppress;
            }

            if (job.def == JobDefOf.Follow)
            {
                Pawn followTarget = job.targetA.Thing as Pawn;
                if (followTarget == null
                    || followTarget.Destroyed
                    || !followTarget.Spawned
                    || followTarget.Downed
                    || followTarget.Map != pawn.Map
                    || !pawn.CanReach((LocalTargetInfo)followTarget, PathEndMode.Touch, Danger.Deadly))
                {
                    job = null;
                    return JobLoopDecision.FallbackVanilla;
                }
            }
            else if (job.def == JobDefOf.AttackMelee || job.def == JobDefOf.Mine)
            {
                Thing target = job.targetA.Thing;
                if (target == null
                    || target.Destroyed
                    || !target.Spawned
                    || target.Map != pawn.Map
                    || !pawn.CanReach((LocalTargetInfo)target, PathEndMode.Touch, Danger.Deadly))
                {
                    job = null;
                    return JobLoopDecision.FallbackVanilla;
                }
            }

            return JobLoopDecision.Keep;
        }

        private static bool IsSameCurrentJob(Pawn pawn, Job candidate)
        {
            Job current = pawn.CurJob;
            if (current == null || current.def != candidate.def)
            {
                return false;
            }

            Thing candidateTarget = candidate.targetA.Thing;
            return candidateTarget != null && current.targetA.Thing == candidateTarget;
        }
    }
}
