<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable>
    <AssemblyName>FireSteelLTSAmmoCompat</AssemblyName>
    <RootNamespace>FireSteelLTSAmmoCompat</RootNamespace>
    <OutputPath>..\1.5\Assemblies\</OutputPath>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Krafs.Rimworld.Ref" Version="1.5.4063" />
    <PackageReference Include="Lib.Harmony" Version="2.3.3" />
  </ItemGroup>
</Project>
